insert into main.CATEGORIA_INGREDIENTE (id_categoria, nombre_categoria)
values  (1, '(Jugos de fruta'),
        (2, 'Aceites vegetales'),
        (3, 'Aceites y Grasas'),
        (4, 'Avena muesli y cereales'),
        (5, 'Aves de corral y aves'),
        (6, 'Bebidas alcohólicas y bebidas'),
        (7, 'Bebidas sin alcohol y bebidas'),
        (8, 'Caramelos y dulces'),
        (9, 'Carne'),
        (10, 'Carne de vacuno y ternera'),
        (11, 'Cerdo'),
        (12, 'Cerveza'),
        (13, 'Comida rápida'),
        (14, 'Embutido'),
        (15, 'Fiambres y Almuerzos'),
        (16, 'Fruta enlatada'),
        (17, 'Frutas tropicales y exóticas'),
        (18, 'Helado'),
        (19, 'Hierbas especias'),
        (20, 'HornearIngredientes'),
        (21, 'Leche y productos lácteos'),
        (22, 'Menudencias y Menudencias'),
        (23, 'Pastas y Fideos'),
        (24, 'Pasteles panes y bollos'),
        (25, 'PatataProductos'),
        (26, 'Pescados y Mariscos'),
        (27, 'Pizza'),
        (28, 'Platos y Comidas'),
        (29, 'Productos de cereales'),
        (30, 'Queso'),
        (31, 'Queso crema'),
        (32, 'Rebanadas De Queso'),
        (33, 'Refrescos y Refrescos'),
        (34, 'Salsas y Aderezos'),
        (35, 'Semillas de nuez'),
        (36, 'Untables'),
        (37, 'Venado y caza'),
        (38, 'Verduras'),
        (39, 'Vino'),
        (40, 'Yogur'),
        (41, 'frutas'),
        (42, 'legumbres'),
        (43, 'pasteles y tartas'),
        (44, 'sopas');